### ISSUE TITLE
Problem to make the project RUN

### ISSUE THREAD

**Issue by choesang** [laktek/realie#7]
Hi!
I read the article on this collaborative tool and got really excited to try it out. 

I am working on a virtual Ubuntu machine with node.js V0.2.6 (I saw that there are compatibility issues with V0.4.+ and express)

FIrst of all, when i do git clone on the project and try to run it, it throws class.js not found exception on express. 
I than saw in the issue 3,  a solution by alexwall(https://github.com/laktek/realie/issues#issue/3)
I cloned his project and followed the instructions. 

I have a redis server up and running. After that app.js and socket.js are started in seperate terminals. The redis server recognizes the connection being made and shows "2 clients connected". The socket.js terminal shows "Listening for connections", that means 
server.addListener("listening", function(){...} is executed.

When i point my chrome browser to: http://localhost:3000/pad, the app.js terminal prints that I connected with a chrome browser. 

My problem is: It does not do any thing after that. It does not show any user connected  nor does the editor synchronizes between the clients when i type in the editor, It shows no sign of connectivity.

Am i missing something really obvious? 

Dying to see the application work

**Comment by laktek** [comment]
Have you checked whether the WebSockets are enabled in your browser? Due to a security glitch, web sockets are disabled by default in the new versions of the Chrome.

**Comment by choesang** [comment]
WebSockets are enabled in my chrome browser.
